# Generated by Django 2.2.7 on 2020-04-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200411_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameId', models.AutoField(primary_key=True, serialize=False)),
                ('team1', models.ForeignKey(blank=True, on_delete='CASCADE', related_name='blueTeam', to='pages.Team')),
                ('team2', models.ForeignKey(blank=True, on_delete='CASCADE', related_name='redTeam', to='pages.Team')),
            ],
        ),
    ]
