# Generated by Django 2.2.7 on 2020-04-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200412_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1', to='pages.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to='pages.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player3', to='pages.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player4', to='pages.Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player5', to='pages.Player'),
        ),
    ]
