# Generated by Django 2.2.7 on 2020-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200418_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
