# Generated by Django 2.2.7 on 2020-04-19 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_player_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='times',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
